// Generated by build_chords.py — manual edits are preserved on rebuild
// Generated: 2026-02-08T21:20:55.550894
const CHORD_SONGS = [
  {
    "title": "As The Deer",
    "key": "C",
    "sections": [
      {
        "type": "verse",
        "label": "Verse 1",
        "lines": [
          "[C]As the [G]deer panteth for the [Am]water",
          "",
          "So my soul [F]longeth after [G]Thee [C]",
          "",
          "[C]You alone [G]are my heart's [Am]desire",
          "",
          "And I long [F]to worship [G]Thee. [C]"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus",
        "lines": [
          "[Am]You alone are my strength [F]my shield [C]",
          "",
          "To [Am]You alone may my spirit [F]yield [E]",
          "",
          "[C]You alone [G]are my heart's [Am]desire",
          "",
          "And I long [F]to worship [G7]Thee [C]"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 2",
        "lines": [
          "[C]You're my friend [G]and you are my [Am]brother",
          "",
          "Even though [F]you are a [G]King [C]",
          "",
          "[C]I love [G]you more than any [Am]other",
          "",
          "So much more [F]than anything   [G] [C]"
        ]
      }
    ]
  },
  {
    "title": "Babel Builders",
    "key": "D",
    "sections": [
      {
        "type": "verse",
        "label": "",
        "lines": [
          "[D]We think that things are going smooth down here",
          "[D]Stackin' bricks up to the atmosphere",
          "You can see a long [G]way down from here [Em] [D]",
          "[D]Why not? is a common refrain",
          "[D]It's gonna happen if you play or if you stay",
          "Oh God [G]--- what are [A]we [D]--- doing?",
          "",
          "[B7]Ba ba ba ba ba Babel",
          "[A]Ba ba ba ba ba [G]Babel, ---- Builders",
          "[B7]Ba ba ba ba ba Babel",
          "[A]Ba ba ba ba ba [G]Babel, ---- Builders",
          "",
          "[D]Look what we have accomplished today",
          "[D]Our name is written in the stone not in the water",
          "Oh [G]no,---- what [A]are you [D]---- doing? [chorus x2]"
        ]
      },
      {
        "type": "bridge",
        "label": "bridge",
        "lines": [
          "[D]Hey Bob, pass me that hammer and chisel",
          "I got one [A]last letter [G]to make",
          "[D]It's pretty special [B]I am signin' my [A]name today",
          "[G]Hoo-ray [Em]",
          "",
          "He looked at me and he said ....",
          "Ba [B]ba ba ba ba ....",
          "[A]Ba ba ba ba ba [G].....",
          "Ba [B]ba ba ba ba .....",
          "[A]Ba ba ba ba ba [G]....",
          "[A]Oh no ----- [G]dear me ---",
          "[A]I fin----ally [G]see"
        ]
      }
    ]
  },
  {
    "title": "Christ be Magnified",
    "key": "C",
    "sections": [
      {
        "type": "intro",
        "label": "Intro",
        "lines": [
          "[C] [G] [F] [C] [G] [F]",
          "",
          "Were [C]creation suddenly [F2]articulate",
          "With a [C]thousand tongues to life one [F2]cry",
          "Then from the [C/E]north to south and [F2]east to west",
          "We'd [C/G]hear \u201cChrist [G]be [C][G][F2]magnified\u201d",
          "",
          "Were the [C]whole earth echoing His [F2]eminence",
          "His [C]name would burst from sea and [F2]sky",
          "From [C/E]rivers to the [F2]mountaintops",
          "We'd hear [C/G]\u201cChrist be [G][C]magnified\u201d  [C2] [C]"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus",
        "lines": [
          "[C]Oh Christ be [Csus/D][F2]magnified",
          "Let His [Csus]praise [Am7]arise",
          "Christ be [Csus]magnified [F2]in me",
          "[C]Oh Christ be [Csus/D][F2]magnified",
          "From the altar of my [Csus]life [Am7]",
          "Christ be [Gsus]magnified [F2]in me"
        ]
      },
      {
        "type": "section",
        "label": "Turn",
        "lines": [
          "[C] [G] [F]",
          "",
          "When every [C]creature finds its inmost [F2]melody",
          "And every [C]human heart its native [F2]cry",
          "Oh then in [C/E]one enraptured [F2]hymn of praise",
          "We'll [C/G]sing Christ [G]be [F2]magnified [C]"
        ]
      },
      {
        "type": "section",
        "label": "Interlude",
        "lines": [
          "[F] [G] [Am] [C/E]"
        ]
      },
      {
        "type": "bridge",
        "label": "Bridge",
        "lines": [
          "[F2]I won't bow to idols",
          "I'll stand [G]strong and worship You",
          "If it [Am7]puts me in the fire",
          "I'll [C/E]rejoice 'cause You're there too",
          "I [F2]won't be formed by feelings",
          "I hold [G]fast to what is true",
          "If the [Am7]cross brings transformation",
          "Then I'll be [C/E]crucified with You",
          "Cause [F2]death is just the doorway",
          "Into [G]resurrection life",
          "If I [Am7]join You in your sufferings",
          "Then I'll [C/E]join You when You rise",
          "And when [F2]You return in glory",
          "With all the [G]angels and the saints",
          "My [Am7]heart will still be singing",
          "And my [G]song will be the same"
        ]
      }
    ]
  },
  {
    "title": "Firm Foundation",
    "key": "G",
    "sections": [
      {
        "type": "intro",
        "label": "Intro",
        "lines": [
          "[C]"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus",
        "lines": [
          "Christ is my firm [C]foundation",
          "The [Am]rock on which I [G]stand",
          "When everything [F]around [C]me is shaken",
          "I've [Am]never been more [G]glad",
          "That I [F]put my faith [C]in Jesus",
          "'Cause He's never [Am]let me down [G]",
          "He's faithful [F]through [C]generations",
          "So why [Am]would He fail now [G]"
        ]
      },
      {
        "type": "tag",
        "label": "Tag",
        "lines": [
          "He [C]won't",
          "He [Am]won't"
        ]
      },
      {
        "type": "verse",
        "label": "Verse",
        "lines": [
          "I've still got joy [C]in chaos",
          "I've got peace [Am]that makes [G]no sense",
          "I won't be [F]going [C]under",
          "I'm not held [Am]by my own [G]strength",
          "F.         C",
          "'Cause I've built my life on Jesus",
          "He's never [Am]let me [G]down",
          "He's [F]faithful in every [C]season",
          "So why [Am]would He fail [G]now"
        ]
      },
      {
        "type": "tag",
        "label": "Tag",
        "lines": [
          "He [C]won't",
          "He [Csus]won't",
          "He won't [Am][G][F]fail",
          "He won't [Am][G][F]fail"
        ]
      },
      {
        "type": "bridge",
        "label": "Bridge",
        "lines": [
          "[F]Rain came [G]and wind blew",
          "But my [C]house was built [Am]on You [G]",
          "[F]I'm [G]safe with You",
          "[C]I'm going to [Am]make [G]it through",
          "[F]Rain came [G]and wind blew",
          "But my [C]house was built [Am]on You [G]",
          "[F]I'm [G]safe with You",
          "[C]I'm going to [Am]make [G]it through"
        ]
      },
      {
        "type": "bridge",
        "label": "Bridge",
        "lines": [
          "[F]I\u2019m going to make [G]it through",
          "[C]\u2018Cause I\u2019m [Am]standing [G]strong on You",
          "[F]I\u2019m going to make [G]it through",
          "\u2018Cause my house [C]was built [Am]on [G]You"
        ]
      }
    ]
  },
  {
    "title": "Good Good Father",
    "key": "D",
    "sections": [
      {
        "type": "verse",
        "label": "",
        "lines": [
          "[D]Oh, I've heard a thousand stories of what they think You're like",
          "[D]But I've heard the tender whisper of love in the dead of night",
          "And You [G][F#/G]tell me [Bm]that You're pleased",
          "And that [Em]I'm never [A]alone",
          "You're a Good, Good [G]Father",
          "It's who [D]You are, [Em]it's who You [A]are, it's who You are",
          "And I'm loved [G]by You",
          "It's who [D]I am, it's [Em]who I am, [A]it's who I am",
          "[D]Oh, and I've seen many searching for answers far and wide",
          "[D]But I know we're all searching, For answers only You provide",
          "'Cause You know just [G]what we need [D/F#]",
          "Before we say [Em]a word [A]",
          "'Cause You are [G]perfect in all [D]of Your ways",
          "You are perfect [Em]in all of [A]Your ways",
          "You are [G]perfect [D]in [A]all of Your ways to us",
          "",
          "[D]Oh, it's love so undeniable, I, I can hardly speak",
          "[D]Peace so unexplainable, I, I can hardly think",
          "",
          "As [G]You call me [D/F#]deeper still",
          "As [Em]You [D/F#]call me deeper still",
          "As [G]You [D/F#]call me deeper still",
          "Into love, [Em][A]love, love"
        ]
      }
    ]
  },
  {
    "title": "Hark the Herald Angels Sing",
    "key": "B",
    "sections": [
      {
        "type": "verse",
        "label": "",
        "lines": [
          "[E]Hark! the herald [B]angels sing,",
          "[E]\u201cGlory to the new [B]born [E]King,",
          "peace on [A/F#]earth, [B]and mercy mild,",
          "[B]God and sinners reconciled!\u201d",
          "[E]Joyful, all ye [A]nations [B]rise,",
          "[E]join the [A]triumph [B]of the skies;",
          "[A]with th\u2019 angelic [A/F#]host proclaim,",
          "[B]\u201cChrist [E]is born in [B][E]Bethlehem!\u201d",
          "[A]Hark! the [A/F#]herald angels sing,",
          "[B]\u201cGlory to [E]the new [B]born [E]King!\u201d",
          "",
          "[E]Christ, by highest [B]heaven adored;",
          "[E]Christ, the everlasting [B][E]Lord;",
          "late in time [A/F#]behold [B]him come,",
          "[B]offspring of a virgin\u2019s womb.",
          "[E]Veiled in flesh [A]the Godhead [B]see;",
          "[E]hail th\u2019 [A]incarnate [B]Deity,",
          "[A]pleased as man [A/F#]with man to dwell,",
          "[B]Jesus, our [E][B]Emmanuel. [E]",
          "[A]Hark! the [A/F#]herald angels sing,",
          "[B]\u201cGlory to [E]the new [B]born [E]King!\u201d",
          "",
          "[E]Hail the heaven-born Prince [B]of Peace!",
          "[E]Hail the Sun of [B][E]Righteousness!",
          "Light and [A/F#]life [B]to all he brings,",
          "[B]risen with healing in his wings.",
          "[E]Mild he lays his [A]glory [B]by,",
          "[E]born that man no [A]more [B]may die,",
          "[A]born to raise [A/F#]the sons of earth,",
          "[B]born to [E]give us [B]second [E]birth.",
          "[A]Hark! the [A/F#]herald angels sing,",
          "[B]\u201cGlory to [E]the new [B]born [E]King!\u201d"
        ]
      }
    ]
  },
  {
    "title": "He Who is to Come",
    "key": "G",
    "sections": [
      {
        "type": "verse",
        "label": "VERSE 1",
        "lines": [
          "There is a [G]day [Gsus]coming",
          "When the old [G][Gsus]will pass away",
          "Every wrong [Em7]will be made right",
          "No darkness, no [C2]night",
          "The Son will [G][Gsus]light the way"
        ]
      },
      {
        "type": "verse",
        "label": "VERSE 2",
        "lines": [
          "There is a King [G][Gsus]coming",
          "The one who conquered death [G]and [Gsus]grave",
          "No more pain and [Em7]no more sorrow",
          "This hope for [C2]tomorrow",
          "Is our [G]hope [Gsus]for today"
        ]
      },
      {
        "type": "chorus",
        "label": "Pre-Chorus",
        "lines": [
          "He who [C2]was, He who [D]is",
          "He who [C2]was, He who is [D]"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus",
        "lines": [
          "He who is to [Gsus]come, [G]",
          "[G2]Christ the Son of [G]man",
          "[Em7]Riding on the clouds with [Em]a crown upon His head",
          "[C2]every eye will see Him,",
          "with nail [Am7]scars in His hands",
          "Hallelujah,    [G/B] [C2][D]Hallelujah!",
          "",
          "Turnaround",
          "[G] [Gsus]"
        ]
      },
      {
        "type": "verse",
        "label": "VERSE 3",
        "lines": [
          "[G]There\u2019s only One [G][Gsus]worthy",
          "Of all glory [G][Gsus]and all praise",
          "All wealth and [Em7]all honor,",
          "speak wisdom and [C2]power",
          "To the Lamb that [G]was [Gsus]slain      (chorus)"
        ]
      },
      {
        "type": "verse",
        "label": "VERSE 4",
        "lines": [
          "He is surely [G][G]coming",
          "Oh can you [G]feel [G]it too?",
          "All this tension growing stronger [Em]",
          "It\u2019s just a sign [C2]He\u2019s getting closer",
          "He\u2019s already on the move    [G] [G2]"
        ]
      },
      {
        "type": "verse",
        "label": "VERSE 5",
        "lines": [
          "The story has [G][Gsus]been written",
          "We all know how it ends            [G] [Gsus]",
          "My future [Em]has an anchor",
          "My eyes are on [C2]the Savior",
          "He\u2019s coming back [G/B]again",
          "He\u2019s coming back again      [D](chorus x 2)"
        ]
      },
      {
        "type": "tag",
        "label": "Tag",
        "lines": [
          "Hallelujah,   [G/B] [C2] Hallelujah! [D]",
          "Hallelujah,   [G/B] [C2] Hallelujah! [D] [D]",
          "",
          "Outro (Repeated x3)",
          "[C2]Come, Lord [G/B]Jesus, come!",
          "Come, Lord [Am]Jesus, come! [G]"
        ]
      }
    ]
  },
  {
    "title": "I Don't Wanna Go",
    "key": "C",
    "sections": [
      {
        "type": "verse",
        "label": "",
        "lines": [
          "Like David [G]and the temple, I want to bring you praise",
          "Like David [C]and his temple plans, Your ways are not my ways",
          "[Em]You don't need me to [D]build a temple",
          "To know that you love me [C]still",
          "",
          "Like [G]Israel on the shore, All I see is crashing waves",
          "Like [C]Israel on the shore, It's through the wild you make a way",
          "[Em]I will go where you go",
          "[D]I will stay where [C]you stay"
        ]
      },
      {
        "type": "chorus",
        "label": "chorus",
        "lines": [
          "'Cause [G]I don't wanna [C]go if you're not going before me",
          "I [Em]don't wanna go if [D]you're not going before me",
          "I [G]don't wanna go if [C]you're not going before me",
          "I [Em]don't wanna go if [D]you're not going before me",
          "",
          "Like Moses [G]in the desert, I want to see the land",
          "Like Moses [C]in the desert, I can't fully see your plan",
          "[Em]Still your love doesn't stop",
          "When I see [D]the land from a [C]mountain top",
          "",
          "Like [G]Peter on the hill, I want to make this my place",
          "Like [C]Peter on the hill, Before your transfigured face",
          "[Em]I will go where you go",
          "[D]I will stay where [C]you stay"
        ]
      },
      {
        "type": "bridge",
        "label": "bridge",
        "lines": [
          "[D]Anywhere you are, I wanna be there",
          "It's [Em]written on my heart",
          "You're all I've [D]ever needed",
          "",
          "[C]Anywhere you go, I [D]wanna be there",
          "It's [Em]written on my soul",
          "You're all I've [D]ever needed [bridge x2]",
          "",
          "Like Jesus [G]in the garden, Will you take this cup from me?",
          "Like Jesus [C]in the garden",
          "You don't call where [D]you won't lead",
          "[Em]I wanna love like you love",
          "[D]I wanna bleed like you [C]bleed"
        ]
      }
    ]
  },
  {
    "title": "Is He Worthy",
    "key": "C",
    "sections": [
      {
        "type": "verse",
        "label": "Verse 1",
        "lines": [
          "Do you feel [G]the world is broken?  We do",
          "Do you feel [Em]the shadows deepen?  We do",
          "But do you know that [C]all the dark won't stop",
          "The light from getting through?  We do [G]",
          "Do you wish [Bm]that you could see it all made new?  We do           [C] [G]"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 2",
        "lines": [
          "Is [G]all creation groaning?  It is",
          "Is a [Em]new creation coming?  It is",
          "Is the glory [C]of the Lord to be",
          "The light within our midst?  It is [G]",
          "Is it [Bm]good that we remind ourselves of this?  It is      [C] [G]"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus 1",
        "lines": [
          "Is [C]anyone worthy? Is anyone [D]whole?",
          "Is [Em]anyone able to break [D]the seal and open the [C]scroll?",
          "The Lion [C]of Judah who conquered [D]the grave",
          "He is [Em]David's root and the Lamb who [D]died to ransom the [C]slave",
          "Is He wor [Em]- thy? [D]Is He wor - [G]thy [C]",
          "Of all [Em]blessing and honor and [D]glo - ry?   [G] [C]",
          "Is He wor [Em]- thy [D]of [C]this?",
          "He [G]is     [Em] [C]"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 3",
        "lines": [
          "Does the Father [G]truly love us?  He does",
          "Does the Spirit [Em]move among us?  He does",
          "And does Jesus [C]our Messiah hold forever those He loves? He does [G]",
          "Does our God [Bm]intend to dwell again with us?  He does  [C] [G]"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus 2",
        "lines": [
          "Is [C]anyone worthy? Is anyone [D]whole?",
          "Is [Em]anyone able to break [D]the seal and open the [C]scroll?",
          "The Lion [C]of Judah who conquered [D]the grave",
          "He is [Em]David's root and the Lamb who [D]died to ransom the [C]slave",
          "From [C]every people and tribe, every nation [D]and tongue",
          "He has made [G]us a kingdom and priests to God [F#]",
          "To [C]reign with the Son",
          "Is He wor [Em]- thy? [D]Is He wor - [G]thy [C]",
          "Of all [Em]blessing and honor and [D]glo - ry?   [G] [C]",
          "Is He wor [Em]- thy [D]of [C]this?",
          "He [G]is     [Em] [C]"
        ]
      },
      {
        "type": "tag",
        "label": "Tag",
        "lines": [
          "[G]He is! [Em]He is!",
          "Is He [C]worthy? Is He [D]worthy?",
          "[G]He is! [Em]He is!",
          "Is He [C]worthy? Is He [D]worthy?",
          "",
          "[C]He [D]is! [G]",
          "",
          "Is He Worthy?"
        ]
      }
    ]
  },
  {
    "title": "Isn\u2019t He Good?",
    "key": "G",
    "sections": [
      {
        "type": "intro",
        "label": "Intro",
        "lines": [
          "[G] [Em] (Isn't He worthy? [C]Isn't He, isn't He worthy?)",
          "[G] [Em] (Isn't He worthy? [C]Isn't He, isn't He worthy?)"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 1",
        "lines": [
          "I was lost [G]and He found me",
          "I was sick [G]and He healed me",
          "I was dead [Em]and He raised [C]me up again [G]"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 2",
        "lines": [
          "I\u205fwas\u205fbound\u205fand [G]He freed\u205fme",
          "Now I [G]stand\u205fin His victory",
          "I was [Em]desperate and He saved me from [C]my sin [G]"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus",
        "lines": [
          "[C] Isn't He good? Isn't He great? [G]Isn't He faithful?",
          "[D] Look at my life, look what He's done, [Em]isn't He able?",
          "[C] Isn't He good? Isn't He great? [G]Isn't He wor - thy? [D]",
          "Oh, He's worthy, [Em]He's worthy, [C]isn't He? [G]"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 3",
        "lines": [
          "Mighty [G]God, Jehovah",
          "Holy One, [G]Messiah",
          "All the glory [Em]to our r\u0435surrected [C]King, yeah [G]"
        ]
      },
      {
        "type": "bridge",
        "label": "Bridge",
        "lines": [
          "[G] Isn't He worthy? Isn't He, isn't He worthy?",
          "[D] Isn't He worthy? Isn't He, isn't He worthy?",
          "[C] Yes He is, our [D]God is worthy",
          "",
          "[G] Isn't He worthy? Isn't He, isn't He worthy?",
          "[D] Isn't He worthy? Isn't He, isn't He worthy?",
          "[C] Yes He is, our [D]God is worthy",
          "",
          "[Em] Isn't He worthy? Isn't He, isn't He worthy?",
          "[D] Isn't He worthy? Isn't He, isn't He worthy?",
          "[C] Yes He is, our [D]God is [G/B][C]worthy",
          "[D]Yeah"
        ]
      }
    ]
  },
  {
    "title": "Matt 6: Don\u2019t Worry",
    "key": "F",
    "sections": [
      {
        "type": "verse",
        "label": "",
        "lines": [
          "[C]Take no thought [F]for your life,",
          "what you [G]eat,",
          "what you drink; [Am]",
          "your body, [F]or clothes",
          "[C]Is not life [F]more than meat,",
          "and the [Am]body [G]more than [F]clothes?",
          "[F]It is, it is"
        ]
      },
      {
        "type": "chorus",
        "label": "chorus 1",
        "lines": [
          "Seek [C]ye [G]first the kingdom of God,",
          "and His [Am][F]righteousness;",
          "and all [C]these things [G]shall be added to you.",
          "",
          "[Am] [F] Don\u2019t Worry",
          "",
          "[C]Behold the birds [F]of the air:",
          "They don\u2019t [G]sow,",
          "Or [Am]reap,",
          "nor gather [F]in barns;",
          "[C]yet your heavenly [F]Father, [Am]He feeds [G]and cares [F]for them.",
          "Are you [Am]not worth [G]more than [F]they?",
          "[F]You are, you are",
          "",
          "[C]Behold the lilies [F]of the field,",
          "How they [G]grow; they [Am]don\u2019t toil",
          "[F]Nor do they spin:",
          "[C]And yet I [F]say unto you,",
          "Not even [Am]Solomon was [G]dressed like [F]this.",
          "if [Am]God so [G]clothes the [F]grass",
          "How much [Am]more shall He [G]clothe [F]you?",
          "[F]He will, He will"
        ]
      },
      {
        "type": "bridge",
        "label": "bridge",
        "lines": [
          "So [F]take no thought of what you\u2019ll eat",
          "[G]Take no thought of what you\u2019ll drink,",
          "[Am]Take no thought for what you\u2019ll wear,",
          "[F]Your Father knows and cares"
        ]
      },
      {
        "type": "chorus",
        "label": "chorus 2",
        "lines": [
          "Seek [C]ye [G]first the kingdom of God,",
          "and His [Am][F]righteousness;",
          "and all [C]these things [G]shall be added to you.",
          "",
          "[Am] [G] [F]Don\u2019t Worry         Don\u2019t worry",
          "[Am] [G] [F]Don\u2019t Worry         Don\u2019t worry",
          "He\u2019s [F]coming soon [C]"
        ]
      }
    ]
  },
  {
    "title": "Never Once",
    "key": "D",
    "sections": [
      {
        "type": "verse",
        "label": "Verse 1",
        "lines": [
          "[G]Standing on this mountaintop",
          "[D]Looking just how far we've come",
          "[Em]Knowing that for every step",
          "[C]You were with us"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 2",
        "lines": [
          "[G]Kneeling on this battle ground",
          "[D]Seeing just how much You've done",
          "[Em]Knowing every victory, Is",
          "[C]Your power in us"
        ]
      },
      {
        "type": "chorus",
        "label": "Pre-Chorus",
        "lines": [
          "[C]Scars and struggles on the way",
          "[D]But with joy our hearts can say",
          "[Em]Yes, our hearts [D]can say [C]"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus 1",
        "lines": [
          "[G]Never once did we ever walk alone",
          "[Em]Never once did You leave us on our own",
          "[C]You [G]are [Em]faithful, God, [D]You are faithful",
          "[C]You [G]are [Em]faithful, God, [D]You are faithful"
        ]
      },
      {
        "type": "bridge",
        "label": "Bridge",
        "lines": [
          "[C]Scars and struggles on the way",
          "[D]But with joy our hearts can say",
          "[Em]Never once did",
          "[D]we ever walk alone",
          "[C]Carried by Your constant grace",
          "[D]Held within Your perfect peace",
          "[Em]Never once, no, we never",
          "[D/F#]walk alone",
          "",
          "Ending Chorus",
          "",
          "Never once did we ever walk alone",
          "",
          "Never once did You leave us on our own",
          "",
          "You are faithful, God, You are faithful",
          "[G]Every step we are breathing in Your grace",
          "[Em]Evermore we'll be breathing out Your praise",
          "[C]You [G]are [Em]faithful, God, [D]You are faithful",
          "[C]You [G]are [Em]faithful, God, [D]You are faithful"
        ]
      }
    ]
  },
  {
    "title": "Reality",
    "key": "G",
    "sections": [
      {
        "type": "verse",
        "label": "",
        "lines": [
          "Ej = james Taylor type E minus the hi e string, starts on the a string (doesn\u2019t use low E)",
          "E/Ej = open E",
          "",
          "Ej \t     G/Ej\t\t    F#/Ej\t   E/Ej \t\tF#/Ej G/Ej F#/Ej",
          "I\u2019m seein\u2019 things --- that aren\u2019t  real\t\tOh\u2026",
          "",
          "Ej\t      G/Ej\t  F#/Ej\tE/Ej \t\t\tF#/Ej G/Ej F#/Ej",
          "I\u2019m hearing voices --- of the dead\t\tOh\u2026.",
          "",
          "Ej        G/Ej\t            F#/Ej\tE/Ej \t\tF#/Ej G/Ej F#/Ej",
          "Unreality is crashing down on me\t\tOh\u2026",
          "",
          "Ej                G/Ej\t               F#/Ej\tE/Ej \t\tF#/Ej G/Ej F#/Ej\t\tF#/Ej \u2013 two measures",
          "this sinking sand is swallowing down man\tOh\u2026",
          "",
          "[G] [A] [G] [A]",
          "",
          "[G]Rising [A]waters, [G]feet leave the ground",
          "[G]Floating the [A]ocean, [G]shifting around",
          "[G]I need and [A]anchor, [G]some solid ground",
          "[G]I need [A]a place, to [Em]lay my [G]head [C]down [D]",
          "",
          "(down strumming starts)",
          "G (one measure)",
          "[G] [C] [Em](chorus [C]x2)                 (2nd Chorus)",
          "[G]You are reality     [G] [G]You are!    You are!",
          "[C]You are reality     [C] [C]You are!    You are!",
          "[Em]You are reality     [Em] [Em]You are!    You are!",
          "[C]You are, You are, You [C]are       You [C]are!    You [G]are! and You\u2019ll always be, You are.",
          "",
          "[G]The First, [C]The last, [Em]The King, Who seeks, [C]the Bride, [G]His Church, [C]to make, [Em]Her whole.   (to [C]chorus)",
          "",
          "[G]The Rock, on [C]which, I stand, [Em]I\u2019ll never be [C]shaken again, the [G]END, Amen, [C]Holy [Em]Holy Holy [C]You are! (to chorus)",
          "",
          "[G]The Rock, [C]on which, I [Em]stand, I\u2019ll [C]never be shaken again, the END, [G]Amen, Holy [C]Holy Holy [Em]You are! [C](to 2nd chorus)"
        ]
      }
    ]
  },
  {
    "title": "Run to the Father",
    "key": "G",
    "sections": [
      {
        "type": "verse",
        "label": "",
        "lines": [
          "[G2]I've carried [Am]a burden",
          "[Em]For too [C2]long on my own",
          "[G2]I [Am]wasn't created",
          "[Em]To bear [C2]it alone",
          "[G2]I hear [Am]Your invitation",
          "[Em]To let [C2]it all go",
          "I see it now [G2]",
          "I'm laying [Am]it down",
          "And I know [Em]that [D]I need [C2]You",
          "",
          "I run to the [G2]Father",
          "I fall [Am]into grace",
          "I'm done [Em]with the hiding",
          "No reason to [C2]wait",
          "My heart [G2]needs a surgeon",
          "My soul needs a [Am]friend",
          "So I'll run to the Father [Em]",
          "Again [C2]and again",
          "And again [G2]and again",
          "",
          "[Am]Oh, [Em]oh, [C2]oh",
          "",
          "[G2]You saw my [Am]condition",
          "[Em]Had a plan from the [C2]start",
          "[G2]Your Son for [Am]redemption",
          "[Em]The price for my heart [C2]",
          "[G2]And I don't [Am]have a context",
          "[Em]For that [C2]kind of love",
          "I don't [G2]understand",
          "I can't [Am]comprehend",
          "All I [Em]know [D]is I [C2]need You",
          "",
          "My heart has been in Your [Em]sights   [C2] G/B         D",
          "Long before my first breath",
          "Running [G/B]into Your [C2]arms",
          "Is running [G/B]to life from [D]death",
          "And I feel this rush deep [Em]in my chest [C2]",
          "Your mercy is [G/B]calling out [D]",
          "Just [Em]as I am [C2]You pull me in",
          "And I know I need You now [G/B] [D]"
        ]
      },
      {
        "type": "chorus",
        "label": "chorus 1+2 outro",
        "lines": [
          "I run to [G2]the Father",
          "I fall [Am]into grace",
          "I'm done [Em]with the hiding",
          "No reason to [C2]wait",
          "My heart [G2]needs a surgeon",
          "My soul needs a [Am]friend",
          "So I'll run to the Father [Em]",
          "Again [C]and again",
          "",
          "I run to the Father [G2]",
          "I fall [Am]into grace",
          "I'm done [Em]with the hiding",
          "No reason to [C2]wait",
          "And my heart [G2]found a surgeon",
          "My soul [Am]found a friend",
          "So I'll [Em]run to the Father",
          "Again and [C2]again",
          "And again [G2]and again",
          "",
          "Oh,  [Am] oh [Em]",
          "Again and again    [C2] [G2]",
          "",
          "Oh,  [Am] oh [Em]",
          "Again and again    [C2] [G2]"
        ]
      }
    ]
  },
  {
    "title": "The Spirit Says Arise",
    "key": "C",
    "sections": [
      {
        "type": "verse",
        "label": "",
        "lines": [
          "[G]The voice of God, [C]Almighty Warrior,",
          "[G]declaring war, Hear [C]His command, [Am]you are a [Em]chosen generation,",
          "[C]a mighty force [D]in the land"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 2:",
        "lines": [
          "All of creation now is waiting",
          "to see the righteous take their stand;",
          "moving out in His anointing,",
          "fulfilling God's eternal plan"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus:",
        "lines": [
          "[G]Arise, this [C]is the final [D]hour.",
          "[G]Arise, ye [C]soldiers of the [D]King.",
          "[G]Arise, put [C]on your holy [D]armor",
          "No, the [C]gates of hell [D]will [G]not [F#][Em]prevail",
          "so arise, [C]the spirit says [D]arise"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 3:",
        "lines": [
          "The army of God is now assembled,",
          "a people filled with power and might.",
          "The time is now no hesitation,",
          "take up your swords, stand up and fight"
        ]
      }
    ]
  },
  {
    "title": "the truth shall set you free",
    "key": "D",
    "sections": [
      {
        "type": "verse",
        "label": "",
        "lines": [
          "[D]The truth shall [A]set you free",
          "Do you [G]believe ME? [D]",
          "",
          "All liars go to hell",
          "Where there father dwells, deep under ground",
          "",
          "[Em]But David? [F#]But Peter? [D]What [G]of Jacob the deceiver?",
          "God forgives, [Bm]in repentance [G][D]saves",
          "",
          "Go and sin no more",
          "God even saves whores",
          "",
          "Turn you eyes from evil things",
          "Live a simple quite life",
          "",
          "[Em]In Jesus [F#]Christ you [A]find all [D]the excitement you\u2019ll ever need",
          "If you\u2019ll turn to him you\u2019ll see, he\u2019s the one the one you needed, turn to Him."
        ]
      }
    ]
  },
  {
    "title": "The Vow \u2013 Cody Carnes",
    "key": "G",
    "sections": [
      {
        "type": "intro",
        "label": "Intro",
        "lines": [
          "[G] [Bm] [C] [Am7]"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 1",
        "lines": [
          "[G] I'm not here for the promise",
          "[Bm] I'm here for Your presence",
          "[C] In joy and in sorrow",
          "[Am7] My love\u2005will\u2005remain",
          "[G] I don't need\u2005all the answers",
          "[Bm] I just wanna be\u2005close",
          "[C] In mourning and dancing",
          "[Am7] My love will remain"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus",
        "lines": [
          "[G]I need nothing [Bm]but\u205fYou\u205fJesus",
          "[C]All\u205fI'm after [Am7]is\u205fYour heart",
          "[G]Destination [Bm]doesn't\u205fmatter",
          "[C]When the journey's [Am7]where You are"
        ]
      },
      {
        "type": "section",
        "label": "Instrumental",
        "lines": [
          "[G] [Bm] [C] [Am7]"
        ]
      },
      {
        "type": "verse",
        "label": "Verse 2",
        "lines": [
          "[G] Wherever we're going",
          "[Bm] Wherever we stay",
          "[C] You have my surrender",
          "[Am7] My love will remain",
          "[G] And if You are the fire",
          "[Bm] I won't fear the flame",
          "[C] I'll burn for You madly",
          "[Am7] My love will remain"
        ]
      },
      {
        "type": "bridge",
        "label": "Bridge",
        "lines": [
          "[G] I just want to be, [Bm]just want to be where You are",
          "I [C]just want to be, [Am7]just want to be with You"
        ]
      }
    ]
  },
  {
    "title": "You Cannot Be Stopped",
    "key": "A",
    "sections": [
      {
        "type": "verse",
        "label": "",
        "lines": [
          "(Phil Wickam & ChrisQuilala)",
          "",
          "Verse1",
          "[D] The dark tried to hide You",
          "And steal You [A]away",
          "[D] Death tried to keep You",
          "Inside of the grave [A]",
          "[F#m] The enemy fought You",
          "He tried but he lost [E]",
          "[D] You cannot be stopped [A]",
          "",
          "Verse2",
          "[D] When we cried for freedom",
          "You tore down the walls [A]",
          "[D] The weight of our burdens",
          "You carried it all [A]",
          "[F#m] Our fears and our failures",
          "Hang dead on the cross [E]",
          "[D] You cannot be [A]stopped"
        ]
      },
      {
        "type": "chorus",
        "label": "Chorus",
        "lines": [
          "Mover of [D]mountains, breaker of chains [A]",
          "Jesus has triumphed, [E]over the grave [F#m]",
          "Sing hallelujah, [D]the battle is won [A]",
          "Nothing can stand, [E]against our God [A]",
          "",
          "Verse3",
          "[D] We stand on Your victory",
          "We shout out Your praise [A]",
          "[D]Miracle maker",
          "You\u2019re mighty to [A]save",
          "[F#m] Awesome in power",
          "Relentless in love [E]",
          "[D] You cannot be stopped [A]"
        ]
      },
      {
        "type": "bridge",
        "label": "Bridge",
        "lines": [
          "[A] There\u2019s nothing that can stop our God",
          "[F#m] There\u2019s nothing that can stop our God",
          "[E] There\u2019s nothing that can stop our God",
          "There is nothing, [D]there is nothing [E]"
        ]
      }
    ]
  }
];
